project_id = "gvjvwirlgzrmmeekpyzh"

[functions.invite-client-user]
verify_jwt = false

[functions.operational-brain]
verify_jwt = false

[functions.ai-360-agent]
verify_jwt = false

[functions.ai-360-personal]
verify_jwt = false

[functions.ai-help-assistant]
verify_jwt = false

[functions.ai-help-personal]
verify_jwt = false

[functions.create-collaborator]
verify_jwt = false

[functions.dispatch-webhook]
verify_jwt = false

[functions.notify-task-status]
verify_jwt = false

[functions.whatsapp-tools]
verify_jwt = false